#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 The AxonOS Project / Denis Yermakou <connect@axonos.org>
"""The social card is the one image most people see before the site.

It used to be a committed binary with no source. Nothing in the repository
could read it, so nothing could tell that it advertised "auto-refreshed every
6h" while the README, the page footer, the changelog and the workflow cron all
said three hours. It was wrong for as long as it took someone to look at a
shared link and then look at the site.

It is generated by `scripts/build_og_image.py` now, from
`assets/foundation-banner.jpg`, with the cadence read out of the deploy
workflow rather than typed. These checks use only the standard library, so they
run wherever the suite runs; the byte-for-byte comparison against the generator
lives in CI, where Pillow is installed.
"""
from __future__ import annotations

import pathlib
import re
import struct

ROOT = pathlib.Path(__file__).resolve().parents[1]


def png_size(path: pathlib.Path) -> tuple[int, int]:
    """Width and height from the IHDR chunk, without an image library."""
    data = path.read_bytes()
    assert data[:8] == b"\x89PNG\r\n\x1a\n", f"{path.name} is not a PNG"
    return struct.unpack(">II", data[16:24])


def test_the_card_is_the_size_every_platform_expects():
    w, h = png_size(ROOT / "og-image.png")
    assert (w, h) == (1200, 630), f"og-image.png is {w}x{h}, not 1200x630"


def test_the_card_has_a_source_and_a_generator():
    assert (ROOT / "assets" / "foundation-banner.jpg").exists(), \
        "the artwork the card is built from is not in the repository"
    assert (ROOT / "scripts" / "build_og_image.py").exists(), \
        "the card has no generator, so its text cannot be checked against anything"


def test_the_generator_reads_the_cadence_rather_than_stating_it():
    src = (ROOT / "scripts" / "build_og_image.py").read_text(encoding="utf-8")
    assert "pages.yml" in src and "cron" in src, \
        "the cadence must be read from the workflow, not written into the card"
    # And no literal hour figure anywhere in the drawing code.
    drawing = src[src.index("def build("):]
    assert not re.search(r"every\s+\d+\s*h", drawing), \
        "a refresh cadence is hard-coded in the generator"


def test_the_cadence_the_generator_would_read_is_the_real_one():
    """Three hours, and every surface has to agree with the cron that sets it."""
    workflow = (ROOT / ".github" / "workflows" / "pages.yml").read_text(encoding="utf-8")
    m = re.search(r"cron:\s*['\"]\s*\d+\s+\*/(\d+)", workflow)
    assert m, "no schedule in pages.yml"
    hours = int(m.group(1))
    assert hours == 3, f"the deploy cron says every {hours}h"

    readme = (ROOT / "README.md").read_text(encoding="utf-8")
    assert re.search(r"every three hours|every 3 hours|3-hourly", readme), \
        "the README no longer states the cadence the cron actually uses"
    stale = re.findall(r"every\s+(\d+)\s*h(?:ours)?\b", readme)
    wrong = [h for h in stale if h not in ("3", "three")]
    assert not wrong, f"the README states a cadence of {wrong} hours somewhere"
